# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h_-25cA7Hm-o6uDq9qyuFRQnihCc9vDf
"""

script_content = """\
# Import necessary libraries
pip install prophet

import pandas as pd

# Read the dataset
df = pd.read_csv('/content/Dataset- Superstore (2015-2018) (2).csv')

# Display category value counts
df['Category'].value_counts()

# Filter data for Office Supplies
OS = df.loc[df['Category'] == 'Office Supplies']
OS.head(5)

# Display the starting and ending dates
print('Starting date:', OS['Order Date'].min())
print('Ending date:', OS['Order Date'].max())

# Drop irrelevant variables
cols = ['Row ID', 'Order ID', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', \
        'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category']
"""


output_path = '/mnt/data/demand_forecast.py'
with open(output_path, 'w', encoding='utf-8') as script_file:
    script_file.write(script_content)

output_path